[package]
name = "trebody"
version = "0.1.0"
authors = ["Adam Stein <adaminsky@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.12"
termion = "1.5"
